# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignifyLightControl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SignifyLightControl
    pod "MBCircularProgressBar"
    pod 'UICircularProgressRing'
    pod 'KDCircularProgress'
    pod 'Firebase/Core' 
    pod 'Firebase/Database' 




end
